### PR TITLE
Use parse data to extract staticexports from source text

### LINKED ISSUE #20: Bug when exporting a function with unindented lines
If a function has many arguments, we often move the arguments onto their own lines, like this:

```r
foo <- function(
  argument_1,
  argument_2 = "long default value..."
) {
  # function body
}
```

However, `staticimports` fails to properly import functions if there are any unindented lines before the final closing `}`, yielding the following invalid import:
```r
foo <- function(
  argument_1,
  argument_2 = "long default value..."
) {
```

This forces authors to ensure all lines of their function are indented, like so:

```r
foo <- function(
  argument_1,
  argument_2 = "long default value..."
  ) {
  # function body
}
```

Is it possible for `staticimports::import()` to look specifically for an unindented `}` instead of stopping at any unindented line?

### PR DESCRIPTION
**Pull request by rossellhayes**
This PR refactors `process_source_text_one()` to extract object definitions from source text using R's parse data.

For example, with this input:

``` r
writeLines("
# Comment attached to f
f <- function() 123

# Comment separated from g

g <- local(
  function() {
    x <- 123
    x
  }
)

# Comment separated from x

# Comment attached to x
x <- list(
  # Comment within the definition
  1,
  2,
  3
)

`%infix%` <- function(lhs, rhs) lhs
",
file <- tempfile()
)
```

we get this result:

``` r
process_source_text_one(readLines(file))
#> $f
#> [1] "# Comment attached to f"
#> [2] "f <- function() 123"    
#> 
#> $g
#> [1] "g <- local("   
#> [2] "  function() {"
#> [3] "    x <- 123"  
#> [4] "    x"         
#> [5] "  }"           
#> [6] ")"             
#> 
#> $x
#> [1] "# Comment attached to x"          
#> [2] "x <- list("                       
#> [3] "  # Comment within the definition"
#> [4] "  1,"                             
#> [5] "  2,"                             
#> [6] "  3"                              
#> [7] ")"                                
#> 
#> $`%infix%`
#> [1] "`%infix%` <- function(lhs, rhs) lhs"
```

<sup>Created on 2022-10-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Closes #20.

### CODE REVIEW

**Comment by rossellhayes** [comment]
One issue with this approach is that assignments with `=` instead of `<-` can only be supported on R >= 3.6. In previous versions of R, the parse data did not track assignments containing `=` in a way that makes it easy to determine their object definition.

On the other hand, the previous approach explicitly only supported `<-` regardless of R version, so this is not a regression.

File: R/import.R [hunk 1]
```diff
@@ -100,10 +100,8 @@ import_objs <- function(
   } else {
     env <- new.env()
     files <- dir(source, pattern = "\\.[r|R]$", full.names = TRUE)
-    source_text <- list() # The contents of each file
     for (file in files) {
       source(file, local = env, keep.source = TRUE)
-      source_text[[file]] <- readLines(file)
```
Comment (wch) [inline R/import.R:106]: With the old code, the `source`-ing of the files is right next to the `readLines()`. This is good because it keeps the running of the code and reading of the code together. With the new version, the reading of the files happens somewhere else completely. Unless there's a really good reason for that, I'd prefer to keep things as they were.

File: R/process_source.R [hunk 2]
```diff
@@ -1,131 +1,71 @@
...
-        current_chunk$reset()
-      }
-    }
+# Given a file, process the text and return a named list of objects.
+process_source_file_one <- function(file) {
+  parse_data <- utils::getParseData(parse(file = file, keep.source = TRUE))
+  text <- readLines(file)
+
+  assignment_ops <- parse_data[
+    parse_data$token %in% c("LEFT_ASSIGN", "EQ_ASSIGN", "RIGHT_ASSIGN"),
```
Comment (wch) [inline R/process_source.R:13]: Can you remove `RIGHT_ASSIGN`? It obviously is valid R code, but I don't think it's necessary to support it for staticimports, and I don't want to encourage people to use it.

File: R/process_source.R [hunk 3]
```diff
@@ -1,131 +1,71 @@
...
+  ]
+  # Assignments are the parent expressions of assignment operators
+  assignments <- parse_data[parse_data$id %in% assignment_ops$parent, ]
+  # Top-level expressions have a parent attribute of 0
+  object_definitions <- assignments[assignments$parent == 0, ]
+
+  staticexports <- vector("list", nrow(object_definitions))
+
+  for (i in seq_len(nrow(object_definitions))) {
+    object_definition <- object_definitions[i, ]
```
Comment (wch) [inline R/process_source.R:23]: This is minor, but I don't like iterating over rows of the data frame and slicing out a single row each time, because, it's slow. (Creating data frames is slow in general in R.)

Also, using a value from the one-row data frame and relying on the fact that's it's a one-element vector (as in `object_definitions$id` instead of `object_definitions$id[1]`), feels weird to me.

Can you pull out the necessary values into a list instead? With a list, the shape of the data is clearer, and it will be faster.

File: R/process_source.R [hunk 4]
```diff
@@ -1,131 +1,71 @@
...
+      object_definition$line1 - leading_comments$line1 <=
+        rev(seq_len(nrow(leading_comments))),
+    ]
+
+    staticexport_lines <- seq(
+      min(leading_comments$line1, object_definition$line1),
+      max(leading_comments$line2, object_definition$line2)
+    )
+    staticexport_text <- text[staticexport_lines]
+    staticexports[[i]] <- staticexport_text
```
Comment (wch) [inline R/process_source.R:44]:
```suggestion
    staticexport_line_idx <- seq(
      min(leading_comments$line1, object_definition$line1),
      max(leading_comments$line2, object_definition$line2)
    )
    result[[i]] <- text[staticexport_line_idx]
```

File: R/process_source.R [hunk 5]
```diff
@@ -1,131 +1,71 @@
...
+
+  assignment_ops <- parse_data[
+    parse_data$token %in% c("LEFT_ASSIGN", "EQ_ASSIGN", "RIGHT_ASSIGN"),
+  ]
+  # Assignments are the parent expressions of assignment operators
+  assignments <- parse_data[parse_data$id %in% assignment_ops$parent, ]
+  # Top-level expressions have a parent attribute of 0
+  object_definitions <- assignments[assignments$parent == 0, ]
+
+  staticexports <- vector("list", nrow(object_definitions))
```
Comment (wch) [inline R/process_source.R:20]:
```suggestion
  result <- vector("list", nrow(object_definitions))
```

Also, you don't have to change this, but FWIW, preallocation of the list won't provide much performance benefit, if any, when there's only a single reference to the object, as there is in this code. With recent R versions, it will grow the list in place (if possible, which is true most of the time) when there's only one reference to it.

File: R/process_source.R [hunk 6]
```diff
@@ -1,131 +1,71 @@
...
-# Given text like "foo <- function() {", return "foo". Also handles the case
-# where the name is surounded with backticks.
-extract_object_name <- function(txt) {
-  result <- sub("^(\\S+).*", "\\1", txt)
+  result <- utils::getParseText(parse_data, object_name_expr$id)
 
   # Remove backticks, so that strings like "`%||%`" are converted to "%||%"
   if (grepl("^`\\S+`$", result)) {
-    result <- sub("^`(\\S+)`$", "\\1", result)
+    result <- sub("^`(\\S+)`$", "\\1", result, perl = TRUE)
```
Comment (wch) [inline R/process_source.R:66]: Is the `perl=TRUE` change necessary?

File: R/process_source.R [hunk 7]
```diff
@@ -1,131 +1,71 @@
...
-      s
-    },
-    reset = function() {
-      s <<- logical(0)
-    }
-  )
+  staticexports
 }
 
+extract_object_name <- function(parse_data, object_definition, assignment_ops) {
```
Comment (wch) [inline R/process_source.R:50]: It would be clearer to pass in just the `object_id` instead of `object_definition`.

File: R/process_source.R [hunk 8]
```diff
@@ -1,131 +1,71 @@
...
-  )
-  return(FALSE)
-}
+  object_name_expr <- parse_data[
+    parse_data$parent == object_definition$id &
+      if (assignment$token %in% c("LEFT_ASSIGN", "EQ_ASSIGN")) {
+        parse_data$line2 <= assignment$line1 & parse_data$col2 < assignment$col1
+      } else {
+        parse_data$line1 >= assignment$line2 & parse_data$col1 > assignment$col2
+      },
```
Comment (wch) [inline R/process_source.R:59]: Can you move this logic out of the brackets?

File: R/process_source.R (hunk 6 above)
Comment (rossellhayes) [reply R/process_source.R]: My motivation was that `perl = TRUE` gives better performance:

``` r
result <- c("x", "`%%`")
bench::mark(
  "perl = FALSE" = sub("^`(\\S+)`$", "\\1", result),
  "perl = TRUE" = sub("^`(\\S+)`$", "\\1", result, perl = TRUE)
)
#> # A tibble: 2 × 6
#>   expression        min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>   <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 perl = FALSE   20.9µs   22.2µs    40286.        0B        0
#> 2 perl = TRUE    19.4µs   20.3µs    46868.        0B        0
```

<sup>Created on 2022-10-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

However, according to [this Stack Overflow post](https://stackoverflow.com/questions/47240375/regular-expressions-in-base-r-perl-true-vs-the-default-pcre-vs-tre#answer-47251004), it looks like the opposite might be true on Windows.

Given that the performance benefits aren't universal, I reverted in [0085e19](https://github.com/wch/staticimports/pull/21/commits/0085e19590b2d99cbc04cf0d32a0449dfae215e1).

File: R/import.R (hunk 1 above)
Comment (rossellhayes) [reply R/import.R]: That makes sense. I reverted in [d7cf325](https://github.com/wch/staticimports/pull/21/commits/d7cf3251995bccff3eedeb4626a9f891eaa0f6d7).

File: R/process_source.R (hunk 2 above)
Comment (rossellhayes) [reply R/process_source.R]: Got it, [ed9f10e](https://github.com/wch/staticimports/pull/21/commits/ed9f10e3f09f9fd44fdbd74ecc93542245b571fb) removes support for `->`

**Comment by rossellhayes** [comment]
I really appreciate your review! I've pushed changes that I think address all your comments

File: R/process_source.R (hunk 5 above)
Comment (rossellhayes) [reply R/process_source.R]: I didn't know that! Updated in [26cd7de](https://github.com/wch/staticimports/pull/21/commits/26cd7de5a3966f88f845b38cc6781447eced8326)

File: R/process_source.R (hunk 7 above)
Comment (rossellhayes) [reply R/process_source.R]: Good point! Updated in [47370ae](https://github.com/wch/staticimports/pull/21/commits/47370ae48ac2d72d079fbff2c2111a741a4a5c78)

File: R/process_source.R (hunk 8 above)
Comment (rossellhayes) [reply R/process_source.R]: Makes sense, updated in [47370ae](https://github.com/wch/staticimports/pull/21/commits/47370ae48ac2d72d079fbff2c2111a741a4a5c78)

File: R/process_source.R (hunk 3 above)
Comment (rossellhayes) [reply R/process_source.R]: I did a refactor in [47370ae](https://github.com/wch/staticimports/pull/21/commits/47370ae48ac2d72d079fbff2c2111a741a4a5c78) that I'm hoping should address this. I didn't know about the performance penalties for slicing rows from data frames, so that'll be good to keep in mind for the future.

File: R/process_source.R (hunk 5 above)
Comment (wch) [reply R/process_source.R]: Here's some example code demonstrating this:
https://gist.github.com/wch/c5642fa8aef65c9c1d3b076dc9e2b813

**Review by wch — APPROVED** [review]
Looks good!
